// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://buouokneefyfgoswahcr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ1b3Vva25lZWZ5Zmdvc3dhaGNyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1NDE4NjksImV4cCI6MjA3MTExNzg2OX0.0rQqCJ80eBDAVk-yqcBFOrdty-ld2KHksUK8buI6I9U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);